version: "3.9"
services: 
  db:
    platform: linux/x86_64
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'flights_db'
      MYSQL_USER: 'yomz'
      MYSQL_PASSWORD: '@dZumi0991'
      MYSQL_ROOT_PASSWORD: '@dZumi0991'
    volumes:
      - ./data/mysql/db:/var/lib/mysql
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    image: flights/tuts
    depends_on:
      - db