# Generated by Django 4.1.3 on 2022-11-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_flight_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='email_address',
            field=models.EmailField(max_length=70, null=True, unique=True),
        ),
    ]
