# Generated by Django 4.1.3 on 2022-11-13 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_passenger_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='email_address',
            field=models.EmailField(max_length=70, null=True, unique=True, validators=[django.core.validators.EmailValidator(message='Email does not match expected format: example@email.com')]),
        ),
    ]
