# Generated by Django 4.1.3 on 2022-12-24 18:07

import bookings.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_passenger_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='first_name',
            field=models.CharField(max_length=70, validators=[bookings.validators.validate_is_alpha]),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='last_name',
            field=models.CharField(max_length=70, validators=[bookings.validators.validate_is_alpha]),
        ),
    ]
