# Generated by Django 4.1.3 on 2022-12-26 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_passenger_first_name_alter_passenger_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='flight_id',
            new_name='flight',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='passenger_id',
            new_name='passenger',
        ),
    ]
